# SPDX-FileCopyrightText: 2026 Joseph Saiko <https://saiko.dev>
# SPDX-License-Identifier: GPL-3.0-only

# Embeds INPUT's raw bytes into OUTPUT as a C array named SYMBOL, so a
# small binary asset (the window icon, splash bitmap and UI font) ships
# inside the executable instead of needing to be located on disk at
# runtime -- the same reason spectre-qt's app icon goes in via a Qt
# resource (.qrc) rather than a loose file. Invoked via `cmake -P` from an
# add_custom_command (see client/spectre/CMakeLists.txt) since this project has no
# Python/xxd dependency to lean on otherwise.
file(READ "${INPUT}" hex_data HEX)
# One regex pass rather than a per-byte loop: the splash bitmap alone is
# 256 KiB, which a CMake foreach takes a noticeable while to walk.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex_data}")

file(WRITE "${OUTPUT}" "// Generated by embed_binary.cmake from ${INPUT} -- do not edit.\n")
file(APPEND "${OUTPUT}" "inline constexpr unsigned char ${SYMBOL}[] = {${bytes}};\n")
file(APPEND "${OUTPUT}" "inline constexpr unsigned int ${SYMBOL}_len = sizeof(${SYMBOL});\n")
