// SPDX-FileCopyrightText: 2026 Joseph Saiko <https://saiko.dev>
// SPDX-License-Identifier: GPL-3.0-only

// veild's configuration (docs/reference/configuration.md): built-in
// defaults, then /etc/ghost/veild.toml, then /etc/ghost/veild.d/*.toml,
// then flags (main.rs). packaging/config/veild.toml is the shipped, fully
// commented copy; a test holds the defaults below to it.
use std::net::{IpAddr, SocketAddr};
use std::path::{Path, PathBuf};
use std::str::FromStr;
use std::time::Duration;

use anyhow::{bail, ensure, Context, Result};
use preauth::{duration, MaxStartups, PenaltyConfig};
use serde::{Deserialize, Serialize};

pub const DEFAULT_PATH: &str = "/etc/ghost/veild.toml";

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct Config {
    pub lobby: Lobby,
    pub hosts: Hosts,
    pub thin_clients: ThinClients,
    pub web: Web,
    pub gateway: Gateway,
    pub auth: Auth,
    pub state: State,
    pub log: Log,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct Lobby {
    /// The address the lobby listens on. Empty: every address, IPv4 and
    /// IPv6 alike. An IPv4 address serves IPv4 only, an IPv6 one IPv6
    /// only.
    pub address: String,
    /// UDP port for spectre's logins, the joined hosts' channels and
    /// gateway sessions alike.
    pub port: u16,
    /// Veil's lobby identity, which spectre pins on first use and every
    /// joined host pins at `ghostd join`. Long-lived: replacing it means
    /// re-joining every host.
    pub cert: PathBuf,
    pub key: PathBuf,
    /// Present the web certificate ([web] cert/key) to clients' logins and
    /// gateway sessions (ALPN gdp/1) instead of the lobby certificate.
    /// Turn it on when the web certificate is CA-issued for the name
    /// clients dial (`public_address`): clients then trust Veil with no
    /// first-use prompt, and its renewals (reloaded on SIGHUP) never look
    /// like a changed certificate. Joined hosts and thin-client agents
    /// always get the lobby certificate, which they pin; Wisp's greeter
    /// accepts either. Off by default: the default web certificate is the
    /// self-signed one `make install-veil` generates, which no CA vouches
    /// for.
    pub clients_use_web_cert: bool,
    /// The name clients and hosts reach this Veil by, for the `ghostd
    /// join` command the admin UI shows and for gateway redirects. Empty:
    /// this machine's fully qualified hostname.
    pub public_address: String,
}

impl Default for Lobby {
    fn default() -> Self {
        Lobby {
            address: String::new(),
            port: 4442,
            cert: PathBuf::from("/etc/ghost/veil-cert.pem"),
            key: PathBuf::from("/etc/ghost/veil-key.pem"),
            clients_use_web_cert: false,
            public_address: String::new(),
        }
    }
}

/// The joined hosts' channels (`gdp-host/1`).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct Hosts {
    /// How long a join token from the admin UI stays valid.
    #[serde(with = "duration")]
    pub join_token_ttl: Duration,
    /// A host that has sent nothing for this long is offline. Hosts ping
    /// every 10 s.
    #[serde(with = "duration")]
    pub idle_timeout: Duration,
    /// Logins in flight at once on one host's channel.
    pub max_login_streams: u32,
}

impl Default for Hosts {
    fn default() -> Self {
        Hosts { join_token_ttl: Duration::from_secs(3600), idle_timeout: Duration::from_secs(30), max_login_streams: 64 }
    }
}

/// Wisp thin clients (`wisp/1`, thin_clients.rs).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct ThinClients {
    /// The shared key every client presents (64 hex digits in a file,
    /// generated by `make install-veil`). Kept out of this file, which is
    /// edited by hand and printed by `veild -T`.
    pub key: PathBuf,
}

impl Default for ThinClients {
    fn default() -> Self {
        ThinClients { key: PathBuf::from("/etc/ghost/veil-wisp.key") }
    }
}

/// The admin web UI.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct Web {
    /// HTTPS (TCP). Only served when `cert` and `key` are set.
    pub listen: String,
    /// The HTTPS certificate chain and key (PEM), from the admin's CA or
    /// ACME client; reloaded on SIGHUP. Never the lobby pair. The default
    /// is the self-signed pair `make install-veil` generates; empty turns
    /// HTTPS off.
    pub cert: String,
    pub key: String,
    /// Plain HTTP for a reverse proxy in front of the web UI, e.g.
    /// "127.0.0.1:8080". Empty: off. Session traffic never goes here.
    pub http_listen: String,
    /// Members of this group (through NSS) may use the admin UI.
    pub admin_group: String,
    /// A browser user stays signed in to Veil (the host list, and the
    /// admin UI for an administrator) until this long without a request ...
    #[serde(with = "duration")]
    pub portal_idle: Duration,
    /// ... or this long after signing in, however active.
    #[serde(with = "duration")]
    pub portal_max: Duration,
    /// How long after signing in Veil keeps the password for the user's
    /// hosts (sealed, the key in the browser; web/remember.rs), so picking
    /// a host asks for it no second time. Never past `portal_max`; 0: off,
    /// every host asks.
    #[serde(with = "duration")]
    pub remember_password: Duration,
}

impl Default for Web {
    fn default() -> Self {
        Web {
            listen: "[::]:443".to_string(),
            cert: "/etc/ghost/veil-web-cert.pem".to_string(),
            key: "/etc/ghost/veil-web-key.pem".to_string(),
            http_listen: String::new(),
            admin_group: "ghost-admins".to_string(),
            portal_idle: Duration::from_secs(12 * 3600),
            portal_max: Duration::from_secs(7 * 24 * 3600),
            remember_password: Duration::from_secs(12 * 3600),
        }
    }
}

/// Session traffic through Veil (docs/design/veil.md#the-gateway).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct Gateway {
    /// A device in `auto` mode goes direct for clients inside these
    /// networks and through Veil for everyone else. Defaults to RFC 1918
    /// and the IPv6 unique local range.
    pub internal_networks: Vec<String>,
    /// The mode new devices get when they join.
    pub default_mode: DeviceMode,
    /// The largest UDP payload Veil sends on a gateway session, in either
    /// direction. Leave room for tunnels on the client side.
    pub max_udp_payload: u16,
}

impl Default for Gateway {
    fn default() -> Self {
        Gateway {
            internal_networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7"].map(String::from).to_vec(),
            default_mode: DeviceMode::Auto,
            max_udp_payload: 1452,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DeviceMode {
    Direct,
    Gateway,
    Auto,
}

impl DeviceMode {
    pub fn as_str(self) -> &'static str {
        match self {
            DeviceMode::Direct => "direct",
            DeviceMode::Gateway => "gateway",
            DeviceMode::Auto => "auto",
        }
    }
}

impl FromStr for DeviceMode {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self> {
        match s {
            "direct" => Ok(DeviceMode::Direct),
            "gateway" => Ok(DeviceMode::Gateway),
            "auto" => Ok(DeviceMode::Auto),
            _ => bail!("unknown device mode {s:?} (direct, gateway or auto)"),
        }
    }
}

/// The same login policy and pre-auth limits as ghostd's
/// (docs/design/preauth.md), for Veil's own logins: the lobby and the web
/// sign-in.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct Auth {
    pub permit_root_login: bool,
    pub permit_empty_passwords: bool,
    #[serde(with = "duration")]
    pub login_grace_time: Duration,
    pub max_startups: MaxStartups,
    pub penalties: PenaltyConfig,
}

impl Default for Auth {
    fn default() -> Self {
        Auth {
            permit_root_login: false,
            permit_empty_passwords: false,
            login_grace_time: Duration::from_secs(120),
            max_startups: MaxStartups::default(),
            penalties: PenaltyConfig::default(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct State {
    /// Devices, entitlements, join tokens, the audit log. Back it up
    /// together with the lobby key.
    pub database: PathBuf,
}

impl Default for State {
    fn default() -> Self {
        State { database: PathBuf::from("/var/lib/veil/veil.db") }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct Log {
    /// A tracing EnvFilter directive; RUST_LOG overrides it.
    pub level: String,
}

impl Default for Log {
    fn default() -> Self {
        Log { level: "info".to_string() }
    }
}

/// One `[gateway] internal_networks` entry: an address and prefix length.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Cidr {
    addr: IpAddr,
    prefix: u8,
}

impl FromStr for Cidr {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self> {
        let (addr, prefix) = match s.split_once('/') {
            Some((a, p)) => (a, Some(p)),
            None => (s, None),
        };
        let addr: IpAddr = addr.trim().parse().with_context(|| format!("invalid network {s:?}"))?;
        let max = if addr.is_ipv4() { 32 } else { 128 };
        let prefix = match prefix {
            Some(p) => p.trim().parse::<u8>().with_context(|| format!("invalid prefix length in {s:?}"))?,
            None => max,
        };
        ensure!(prefix <= max, "prefix length {prefix} too long in {s:?}");
        Ok(Cidr { addr, prefix })
    }
}

impl Cidr {
    pub fn contains(&self, ip: IpAddr) -> bool {
        match (self.addr, ip.to_canonical()) {
            (IpAddr::V4(net), IpAddr::V4(ip)) => {
                let mask = if self.prefix == 0 { 0 } else { u32::MAX << (32 - self.prefix) };
                u32::from(net) & mask == u32::from(ip) & mask
            }
            (IpAddr::V6(net), IpAddr::V6(ip)) => {
                let mask = if self.prefix == 0 { 0 } else { u128::MAX << (128 - self.prefix) };
                u128::from(net) & mask == u128::from(ip) & mask
            }
            _ => false,
        }
    }
}

impl Config {
    pub fn validate(&self) -> Result<()> {
        self.auth.max_startups.validate()?;
        self.internal_networks()?;
        if let Some(addr) = self.web_listen()? {
            // WebTransport takes the web port over UDP, as the lobby does its own.
            ensure!(addr.port() != self.lobby.port, "web.listen must not use lobby.port ({})", self.lobby.port);
        }
        self.http_listen()?;
        self.lobby_address()?;
        ensure!(self.web.cert.is_empty() == self.web.key.is_empty(), "web.cert and web.key must be set together");
        ensure!(
            !self.lobby.clients_use_web_cert || !self.web.cert.is_empty(),
            "lobby.clients_use_web_cert needs web.cert and web.key"
        );
        ensure!(!self.web.admin_group.is_empty(), "web.admin_group must not be empty");
        ensure!(self.hosts.max_login_streams >= 1, "hosts.max_login_streams must be at least 1");
        ensure!(
            (1200..=65527).contains(&self.gateway.max_udp_payload),
            "gateway.max_udp_payload must be 1200-65527"
        );
        ensure!(!self.hosts.idle_timeout.is_zero(), "hosts.idle_timeout must not be 0");
        tracing_subscriber::EnvFilter::try_new(&self.log.level)
            .with_context(|| format!("log.level {:?} is not a valid filter", self.log.level))?;
        Ok(())
    }

    pub fn internal_networks(&self) -> Result<Vec<Cidr>> {
        self.gateway.internal_networks.iter().map(|n| n.parse().context("gateway.internal_networks")).collect()
    }

    /// None when HTTPS is off (no certificate configured).
    /// `[lobby] address` parsed; None for every address.
    pub fn lobby_address(&self) -> Result<Option<std::net::IpAddr>> {
        if self.lobby.address.is_empty() {
            return Ok(None);
        }
        self.lobby.address.parse().map(Some).with_context(|| format!("lobby.address {:?} is not an IP address", self.lobby.address))
    }

    pub fn web_listen(&self) -> Result<Option<SocketAddr>> {
        if self.web.cert.is_empty() {
            return Ok(None);
        }
        Ok(Some(self.web.listen.parse().with_context(|| format!("web.listen {:?}", self.web.listen))?))
    }

    pub fn http_listen(&self) -> Result<Option<SocketAddr>> {
        if self.web.http_listen.is_empty() {
            return Ok(None);
        }
        Ok(Some(self.web.http_listen.parse().with_context(|| format!("web.http_listen {:?}", self.web.http_listen))?))
    }

    /// `public_address`, or this machine's FQDN when it's empty.
    pub fn public_address(&self) -> String {
        if !self.lobby.public_address.is_empty() {
            return self.lobby.public_address.clone();
        }
        fqdn()
    }
}

/// This machine's fully qualified name, as `hostname -f` prints it, or
/// its plain hostname when that fails.
pub fn fqdn() -> String {
    std::process::Command::new("hostname")
        .arg("-f")
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .or_else(|| nix::unistd::gethostname().ok().and_then(|h| h.into_string().ok()))
        .unwrap_or_else(|| "localhost".to_string())
}

/// Reads veild.toml and its drop-ins. veild runs as its own user, so the
/// files must belong to root (or that user) and not be writable by
/// anyone else: they decide who administers Veil.
pub fn load(path: &Path, required: bool) -> Result<(Config, Vec<PathBuf>)> {
    tomlconf::load(path, required, true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shipped_file_is_the_defaults() {
        let shipped = include_str!("../../../packaging/config/veild.toml");
        let uncommented = tomlconf::uncomment_defaults(shipped);
        assert_ne!(uncommented, shipped, "expected commented-out keys in packaging/config/veild.toml");
        let config: Config = toml::from_str(&uncommented).unwrap();
        assert_eq!(config, Config::default());
    }

    #[test]
    fn defaults_validate_and_round_trip() {
        Config::default().validate().unwrap();
        let dumped = toml::to_string(&Config::default()).unwrap();
        assert_eq!(toml::from_str::<Config>(&dumped).unwrap(), Config::default());
    }

    #[test]
    fn cidrs_match_their_networks() {
        let lan: Cidr = "192.168.1.0/24".parse().unwrap();
        assert!(lan.contains("192.168.1.77".parse().unwrap()));
        assert!(lan.contains("::ffff:192.168.1.77".parse().unwrap()));
        assert!(!lan.contains("192.168.2.1".parse().unwrap()));
        let v6: Cidr = "fd00:1:2::/48".parse().unwrap();
        assert!(v6.contains("fd00:1:2:3::9".parse().unwrap()));
        assert!(!v6.contains("fd00:1:3::9".parse().unwrap()));
        let host: Cidr = "10.0.0.1".parse().unwrap();
        assert!(host.contains("10.0.0.1".parse().unwrap()));
        assert!(!host.contains("10.0.0.2".parse().unwrap()));
        let all: Cidr = "0.0.0.0/0".parse().unwrap();
        assert!(all.contains("8.8.8.8".parse().unwrap()));
        assert!("10.0.0.0/33".parse::<Cidr>().is_err());
        assert!("nonsense/8".parse::<Cidr>().is_err());
    }

    #[test]
    fn validate_catches_mistakes() {
        let mut c = Config::default();
        c.gateway.internal_networks = vec!["10.0.0.0/8".into(), "bogus".into()];
        assert!(c.validate().is_err());
        let mut c = Config::default();
        c.web.cert = "/x.pem".into();
        c.web.key = String::new();
        assert!(c.validate().is_err());
        c.web.key = "/y.pem".into();
        assert!(c.validate().is_ok());
        c.web.listen = "nope".into();
        assert!(c.validate().is_err());
        let mut c = Config::default();
        c.web.listen = format!("[::]:{}", c.lobby.port);
        assert!(c.validate().is_err());
        let mut c = Config::default();
        c.lobby.clients_use_web_cert = true;
        assert!(c.validate().is_ok());
        c.web.cert = String::new();
        c.web.key = String::new();
        assert!(c.validate().is_err());
    }
}
