// SPDX-FileCopyrightText: 2026 Joseph Saiko <https://saiko.dev>
// SPDX-License-Identifier: GPL-3.0-only

// Hand-rolled H.264 SPS/PPS bitstream construction.
//
// VA-API's H.264 encode entrypoint generates slice data itself from
// structured parameter buffers (VAEncSliceParameterBufferH264 etc), but
// expects the *application* to supply the SPS and PPS NAL units verbatim
// (VAConfigAttribEncPackedHeaders advertises SEQUENCE/PICTURE support, not
// "driver generates them"). The values written here must stay in lockstep
// with the VAEncSequenceParameterBufferH264 / VAEncPictureParameterBufferH264
// fields set in vaapi_h264_encoder.cpp — see the comments there.
#pragma once

#include "encode/vaapi/nal_bitstream.hpp"

#include <cstdint>
#include <vector>

namespace wraith::h264 {

// The RBSP writer and emulation-prevention escaping are shared with H.265
// -- see nal_bitstream.hpp.
using nal::BitWriter;
using nal::escape_emulation;

struct SpsParams {
	uint32_t width_px;  // display width (post-cropping)
	uint32_t height_px; // display height (post-cropping)
	uint32_t width_mb;  // padded width in macroblocks (16px each)
	uint32_t height_mb; // padded height in macroblocks
	uint8_t level_idc;
	uint8_t log2_max_frame_num_minus4;
};

// profile_idc is fixed at 77 (Main): CAVLC-compatible, no chroma_format_idc
// block in the SPS (implied 4:2:0), and decodable by effectively everything.
// pic_order_cnt_type is fixed at 2 (POC = 2 * frame_num, derived with no
// extra syntax) since the encoder never reorders frames (no B-frames).
std::vector<uint8_t> build_sps(const SpsParams &params);

// entropy_coding_mode_flag is fixed at 0 (CAVLC) to match the picture
// parameter buffer built in vaapi_h264_encoder.cpp.
std::vector<uint8_t> build_pps();

struct SliceHeaderParams {
	bool is_idr;
	uint32_t slice_type; // VA-API numbering: 2 = I, 0 = P
	uint32_t frame_num;
	uint32_t log2_max_frame_num_minus4;
	uint16_t idr_pic_id;
};

// The syntax elements of slice_header() through the deblocking-filter
// fields -- everything Mesa's radeonsi packed-header parser
// (parseEncSliceParamsH264) actually reads before returning. It stops there;
// the macroblock/slice-data layer is generated by the driver from the
// structured VAEncSliceParameterBufferH264, not from this. See the comment
// on wrap_nal() for why this NAL needs to be sent at all. Assumes
// pic_order_cnt_type=2 (no pic_order_cnt_lsb field), CAVLC, single reference
// (no ref_pic_list_modification, no B slices), matching build_sps()/
// build_pps() and the picture/slice parameter buffers in vaapi_h264_encoder.cpp.
std::vector<uint8_t> build_slice_header_prefix(const SliceHeaderParams &params);

// Wraps `rbsp` (already escaped) with the H.264 Annex-B start code
// (00 00 01) and the 1-byte NAL header (forbidden_zero_bit=0, nal_ref_idc,
// nal_unit_type). Needed both in the final Annex-B output and -- despite
// most VA-API drivers not requiring it in a VAEncPackedHeaderDataBufferType
// buffer -- in what's handed to the driver: Mesa's radeonsi packed-header
// handler (vlVaHandleVAEncPackedHeaderDataBufferTypeH264) scans the buffer
// it's given for a 00 00 01 start code and silently ignores the whole thing
// if it never finds one, so the start code has to be part of the packed
// data itself here, not left for the driver to prepend.
std::vector<uint8_t> wrap_nal(uint8_t nal_ref_idc, uint8_t nal_unit_type,
	const std::vector<uint8_t> &escaped_rbsp);

} // namespace wraith::h264
